
class aluno:
    def __init__(self, nome):...
    def mudarNome(self, novoNome):...
    def dizOi(selt):...
    def dizDeOnde(self):...
    def seEsconda(self):...
    def dizSeuNome(self):...

x = aluno("Jonathan")
y = aluno("andré")
z = aluno("Bianca")

x.dizSeuNome( )
y.dizSeuNome( ) 
z.dizSeuNome( )

